### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by noir2099** [iChun/Sync#239]
I'm trying to find a version of sync that is for 1.18.2 but I can't find it for forge is there one and if not can you please make it work with forge? I love this mod and it's sad that I can't use it.

**Comment by iChun** [comment]
This version of Sync has not been updated past Minecraft 1.12.2. There are plans for me do to it, but not anytime in the immediate future. There have been clones released based on the same idea and concept but as far as I know, they are released for Fabric and generally can be found on CurseForge. 

CurseForge currently remains to be the only place to find proper released & up to date versions of my mods. I have been busy IRL on other things and is hugely a reason why this mod is open sourced, so other people may be able to take up the slack and port the mod to newer versions of Minecraft or learn from the code.

You are more than welcome to do a port to the latest version of Minecraft yourself and submit a pull request for me to review. Otherwise, you will have to settle for the alternatives or wait until I get round to updating myself.

**Comment by noir2099** [comment]
Ok thank you
